### PR TITLE
Migrations fix

### LINKED ISSUE #36: Fix knex migrate errors when running knex:migrate latest
Running ```knex migrate:latest```  
Gives several errors based on the certain files running before others *cough cough*toldyouso*cough cough*

### PR DESCRIPTION
**Pull request by TheDavidKruse**
fixes everything to do with migrations for now

Closes #36

### CODE REVIEW

File: backend/db/migrations/320181205134459_playlist.js [hunk 1]
```diff
@@ -1,11 +1,12 @@
-exports.up = function(knex, Promise) {
+exports.up = (knex, Promise) => {
   return knex.schema.createTable('playlist', table => {
     table.increments('id').primary();
     table.text('title');
-    table.number('uuid');
+    table.integer('user_id').unsigned();
```
Comment (signalnerve) [inline backend/db/migrations/320181205134459_playlist.js]: Why do we need to have two references to `user_id` here? (not a rhetorical question - I genuinely am asking 😄)

Comment (TheDavidKruse) [reply backend/db/migrations/320181205134459_playlist.js]: the ```integer(key).unsigned``` instantiates that there's a positive integer in the (key) column. The ```foreign``` then turns that into a foreign key reference! For some reason you can't instantiate a column that uses foreign unless the column already exists.

**Comment by signalnerve** [comment]
ah, word - works for me
